function(check flag def_prefix item_name)
	if(flag)
		add_definitions("-D__L_${def_prefix}${item_name}")
	endif()
endfunction(check)

function(check_using flag module_name)
	check(${flag} "USE_" ${module_name})
endfunction(check_using)

check_using(${USE_FILEFORMAT} "FILEFORMAT")
check_using(${USE_GRAPHICS} "GRAPHICS")
check_using(${USE_GRAPHICS_OPENGL} "GRAPHICS_OPENGL")
check_using(${USE_GRAPHICS_UI} "GRAPHICS_UI")
check_using(${USE_GRAPHICS_UI_CONTROLS} "GRAPHICS_UI_CONTROLS")
check_using(${USE_MEDIA} "MEDIA")
check_using(${USE_NET} "NET")
check_using(${USE_PLATFORM} "PLATFORM")
check_using(${USE_SERIALIZATION} "SERIALIZATION")
check_using(${USE_TESTING} "TESTING")
check_using(${USE_THREADING} "THREADING")

check(${OPENGL_ACC} "" "OPENGL_ACC")
check(${DIRECTX_ACC} "" "DIRECTX_ACC")
